site_name: openpilot中文文档
site_url: https://docs.comma.ai
repo_url: https://github.com/commaai/openpilot
edit_uri: edit/master/docs
docs_dir: docs
site_dir: docs_site
theme:
  name: material
  favicon: assets/favicon.ico
  logo: assets/logo.png
  font:
    text: Inter
  features:
    - content.code.copy
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: black
      accent: indigo
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: indigo
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/commaai
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/comma_ai
    - icon: fontawesome/brands/discord
      link: https://discord.comma.ai
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/comma_ai
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/comma.ai
  analytics:
    provider: google
    property: G-R6C0CRGX0K
plugins:
  - search
  - glightbox
nav:
  - 首页: zh/index.md
  - 入门指南:
    - getting-started/zh/what-is-openpilot.md
  - 操作指南:
    - how-to/zh/turn-the-speed-blue.md
    - how-to/zh/connect-to-comma.md
  - 概念:
    - concepts/zh/logs.md
    - concepts/zh/safety.md
    - concepts/zh/glossary.md
  - 车型适配:
    - car-porting/zh/what-is-a-car-port.md
    - car-porting/zh/brand-port.md
    - car-porting/zh/model-port.md
  - 贡献:
    - contributing/zh/roadmap.md
    - 贡献指南: https://github.com/commaai/openpilot/blob/master/docs/CONTRIBUTING.md.zh
  - 集成: INTEGRATION.md.zh
  - 限制: LIMITATIONS.md.zh
  - 支持车型: CARS.md
  - 安全: SAFETY.md
  - 模型:
    - selfdrive/modeld/models/README.md.zh
